//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.Hollywood {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.radford.edu/Hollywood", ConfigurationName="Hollywood.MovieInfoServiceSoap")]
    public interface MovieInfoServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getMovie", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication2.Hollywood.Movie getMovie(string title, string released);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.Hollywood.Movie> getMovieAsync(string title, string released);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getActor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication2.Hollywood.Actor getActor(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getActor", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.Hollywood.Actor> getActorAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getDirector", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsApplication2.Hollywood.Director getDirector(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getDirector", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication2.Hollywood.Director> getDirectorAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/searchMovies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable searchMovies(string genre1, string genre2, string rating, string review, string firstyear, string lastyear, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/searchMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> searchMoviesAsync(string genre1, string genre2, string rating, string review, string firstyear, string lastyear, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getPopularActors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getPopularActors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getPopularActors", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getPopularActorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getPopularDirectors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getPopularDirectors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getPopularDirectors", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getPopularDirectorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getPopularMovies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getPopularMovies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getPopularMovies", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getPopularMoviesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getRatings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getRatings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getRatings", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getRatingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getReviews", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getReviews();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getReviews", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getReviewsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getGenres", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getGenres();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.radford.edu/Hollywood/getGenres", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> getGenresAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/Hollywood")]
    public partial class Movie : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string releasedField;
        
        private string reviewField;
        
        private string ratingField;
        
        private string directorField;
        
        private System.Data.DataTable genresField;
        
        private System.Data.DataTable actorsField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string released {
            get {
                return this.releasedField;
            }
            set {
                this.releasedField = value;
                this.RaisePropertyChanged("released");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string review {
            get {
                return this.reviewField;
            }
            set {
                this.reviewField = value;
                this.RaisePropertyChanged("review");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
                this.RaisePropertyChanged("rating");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
                this.RaisePropertyChanged("director");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Data.DataTable genres {
            get {
                return this.genresField;
            }
            set {
                this.genresField = value;
                this.RaisePropertyChanged("genres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Data.DataTable actors {
            get {
                return this.actorsField;
            }
            set {
                this.actorsField = value;
                this.RaisePropertyChanged("actors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/Hollywood")]
    public partial class Director : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.Data.DataTable moviesField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Data.DataTable movies {
            get {
                return this.moviesField;
            }
            set {
                this.moviesField = value;
                this.RaisePropertyChanged("movies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.radford.edu/Hollywood")]
    public partial class Actor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private System.Data.DataTable moviesField;
        
        private string dbmessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Data.DataTable movies {
            get {
                return this.moviesField;
            }
            set {
                this.moviesField = value;
                this.RaisePropertyChanged("movies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string dbmessage {
            get {
                return this.dbmessageField;
            }
            set {
                this.dbmessageField = value;
                this.RaisePropertyChanged("dbmessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MovieInfoServiceSoapChannel : WindowsFormsApplication2.Hollywood.MovieInfoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovieInfoServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication2.Hollywood.MovieInfoServiceSoap>, WindowsFormsApplication2.Hollywood.MovieInfoServiceSoap {
        
        public MovieInfoServiceSoapClient() {
        }
        
        public MovieInfoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovieInfoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieInfoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovieInfoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApplication2.Hollywood.Movie getMovie(string title, string released) {
            return base.Channel.getMovie(title, released);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.Hollywood.Movie> getMovieAsync(string title, string released) {
            return base.Channel.getMovieAsync(title, released);
        }
        
        public WindowsFormsApplication2.Hollywood.Actor getActor(string name) {
            return base.Channel.getActor(name);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.Hollywood.Actor> getActorAsync(string name) {
            return base.Channel.getActorAsync(name);
        }
        
        public WindowsFormsApplication2.Hollywood.Director getDirector(string name) {
            return base.Channel.getDirector(name);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication2.Hollywood.Director> getDirectorAsync(string name) {
            return base.Channel.getDirectorAsync(name);
        }
        
        public System.Data.DataTable searchMovies(string genre1, string genre2, string rating, string review, string firstyear, string lastyear, string keyword) {
            return base.Channel.searchMovies(genre1, genre2, rating, review, firstyear, lastyear, keyword);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> searchMoviesAsync(string genre1, string genre2, string rating, string review, string firstyear, string lastyear, string keyword) {
            return base.Channel.searchMoviesAsync(genre1, genre2, rating, review, firstyear, lastyear, keyword);
        }
        
        public System.Data.DataTable getPopularActors() {
            return base.Channel.getPopularActors();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getPopularActorsAsync() {
            return base.Channel.getPopularActorsAsync();
        }
        
        public System.Data.DataTable getPopularDirectors() {
            return base.Channel.getPopularDirectors();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getPopularDirectorsAsync() {
            return base.Channel.getPopularDirectorsAsync();
        }
        
        public System.Data.DataTable getPopularMovies() {
            return base.Channel.getPopularMovies();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getPopularMoviesAsync() {
            return base.Channel.getPopularMoviesAsync();
        }
        
        public System.Data.DataTable getRatings() {
            return base.Channel.getRatings();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getRatingsAsync() {
            return base.Channel.getRatingsAsync();
        }
        
        public System.Data.DataTable getReviews() {
            return base.Channel.getReviews();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getReviewsAsync() {
            return base.Channel.getReviewsAsync();
        }
        
        public System.Data.DataTable getGenres() {
            return base.Channel.getGenres();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> getGenresAsync() {
            return base.Channel.getGenresAsync();
        }
    }
}
